### ISSUE TITLE
Inc error

### ISSUE THREAD

**Issue by limelect** [HemulGM/HGMGetIt#1]
compiling with d10.2.3 (after fixing var)
 // RadioButtonTools.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_tools.inc};
  RadioButtonStyles.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_styles.inc};
  RadioButtonIoT.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_iot.inc};
  RadioButtonIDPlugins.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_plugins.inc};
  RadioButtonSamples.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_samples.inc};
  RadioButtonIT.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_industry.inc};
 // RadioButtonPython.StylesData['icon.Data.Data'] := {$INCLUDE icons/path_python.inc};
those 2  inc give me error 14.31.18, not valid floating.

pressing download does nothing why? viewing only!!

**Comment by HemulGM** [comment]
you need to run the paths in the files through the browser. This seems to have been fixed in recent versions.
