### ISSUE TITLE
Unresolved external dependencies

### ISSUE THREAD

**Issue by salvadordf** [HemulGM/HGMGetIt#2]
Hi,

I tried to test HGMGetIt but I couldn't build it with Delphi 11.3. The following units have unsatisfied external dependencies : 

- HGI.Main uses DarkModeApi.FMX
- HGI.View.Item uses HGM.FMX.Image
- HGI.View.ItemFull uses HGM.FMX.Image

I installed these packages too and added them to the search path of the package but then I got some other issue with wrong parameters in a LoadFromUrlAsync call : 
- https://github.com/HemulGM/Components
- https://github.com/HemulGM/WindowDarkMode

Thanks so much for this project! It looks awesome!

**Comment by HemulGM** [comment]
Hello. I'll fix it today for sure. More precisely, I already fixed it, but did not push it to github. It will be in 3-4 hours)

**Comment by HemulGM** [comment]
Fixed

**Comment by salvadordf** [comment]
Thanks!
